name: hffm-aedes-risk
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - statsmodels
  - geopandas
  - rasterio
  - netcdf4
  - xarray
  - r-base>=4.3
  - r-mgcv
  - r-data.table
  - r-ggplot2
